### ISSUE TITLE
Trouble to build skills

### ISSUE THREAD

**Issue by JacoboRG12** [FurhatRobotics/example-skills#34]
Hi, i´m trying to build skills but the build fails because gradle cannot access to an url.
![Captura de pantalla 2023-02-10 130718](https://user-images.githubusercontent.com/81679718/218088877-cbeacbd2-4c86-46bc-beff-7a27f26a47c5.png)
I don´t know if it is my problem or it was a writing problem.
I hope your answer. Thank you so much .

**Comment by MathieuRH** [comment]
Hi again, 

You should be able to pull the latest version of the branch and run it now ^^

Best, 
Mathieu
